{% set python_min = '3.10' %}
{% set name = "pyclimo" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyclimo-{{ version }}.tar.gz
  sha256: 5fcedb6aae15e46b73113ae9596800a65dfbf2c37015c401b1bea6067c0f13fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7
    - metpy >=1.5.1
    - numpy >=1.24
    - pandas >=2.2
    - xarray >=2023.1.0
    - netcdf4 >=1.7.1
    - cartopy >=0.21.0
    - xeofs >=3.0.4
    - rasterio >=1.4.3
    - pytz >=2024.1

test:
  imports:
    - pyclimo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/pyclimo
  summary: An Open Source Package For Climate Analysis
  license: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/pyclimo/
  dev_url: https://github.com/edrewitz/pyclimo

extra:
  recipe-maintainers:
    - edrewitz
