{% set python_min = '3.10' %}
{% set name = "pyclimo" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyclimo-{{ version }}.tar.gz
  sha256: 62d2c1ea6ac64a6d24266809864771429a06fffc596efc9930256a767b9ac412

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7
    - metpy >=1.5.1
    - numpy >=1.24
    - pandas >=2.2
    - xarray >=2023.1.0
    - netcdf4 >=1.7.1
    - cartopy >=0.21.0
    - xeofs >=3.0.4
    - rasterio >=1.4.3
    - pytz >=2024.1
    - geopandas >=1.1.0

test:
  imports:
    - pyclimo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/pyclimo
  summary: An Open Source Package For Climate Analysis
  license: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/pyclimo/
  dev_url: https://github.com/edrewitz/pyclimo

extra:
  recipe-maintainers:
    - edrewitz
